# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'api_yandex_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.image = QtWidgets.QLabel(self.centralwidget)
        self.image.setGeometry(QtCore.QRect(10, 80, 781, 491))
        self.image.setText("")
        self.image.setObjectName("image")
        self.longitude = QtWidgets.QLabel(self.centralwidget)
        self.longitude.setGeometry(QtCore.QRect(20, 0, 55, 16))
        self.longitude.setObjectName("longitude")
        self.edit_longitide = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_longitide.setGeometry(QtCore.QRect(80, 0, 113, 22))
        self.edit_longitide.setObjectName("edit_longitide")
        self.lattitude = QtWidgets.QLabel(self.centralwidget)
        self.lattitude.setGeometry(QtCore.QRect(230, 0, 55, 16))
        self.lattitude.setObjectName("lattitude")
        self.edit_lattitude = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_lattitude.setGeometry(QtCore.QRect(280, 0, 113, 22))
        self.edit_lattitude.setObjectName("edit_lattitude")
        self.spn = QtWidgets.QLabel(self.centralwidget)
        self.spn.setGeometry(QtCore.QRect(420, 0, 55, 16))
        self.spn.setObjectName("spn")
        self.edit_spn = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_spn.setGeometry(QtCore.QRect(480, 0, 113, 22))
        self.edit_spn.setObjectName("edit_spn")
        self.type_maps = QtWidgets.QComboBox(self.centralwidget)
        self.type_maps.setGeometry(QtCore.QRect(600, 0, 91, 22))
        self.type_maps.setObjectName("type_maps")
        self.type_maps.addItem("")
        self.type_maps.addItem("")
        self.type_maps.addItem("")
        self.type_maps.setItemText(2, "")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(700, 0, 93, 31))
        self.pushButton.setObjectName("pushButton")
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.longitude.setText(_translate("MainWindow", "Долгота"))
        self.edit_longitide.setText(_translate("MainWindow", "37.530887"))
        self.lattitude.setText(_translate("MainWindow", "Широта"))
        self.edit_lattitude.setText(_translate("MainWindow", "55.703118"))
        self.spn.setText(_translate("MainWindow", "Масштаб"))
        self.edit_spn.setText(_translate("MainWindow", "0.002"))
        self.type_maps.setItemText(0, _translate("MainWindow", "map"))
        self.type_maps.setItemText(1, _translate("MainWindow", "sat"))
        self.type_maps.setItemText(2, _translate("MainWindow", "sat,skl"))
        self.pushButton.setText(_translate("MainWindow", "Показать"))
